.TH doctext 1 "6/23/2019" " " ""
.SH NAME
doctext \-  Generate documentation pages from source files 
.SH SYNOPSIS
.nf
doctext [ -mpath path ] [ -ext n ] [ -I filename ] [ -latex ]
[ -html ] [ -index filename ] [ -indexdir filename ]
[ -jumpfile filename ] [ -outfile filename ]
[ -mapref filename ] [ -nolocation ] [ -location ]
[ -defn defnfile ] [ -dosnl ] [ -skipprefix name ]
[ -ignore string ] [ -oldargstyle ]
[ -heading string ] [ -basedir dirname ] filenames
[ -Wargdesc ] [ -Wnone ]
.fi

.SH INPUT PARAMETERS
.PD 0
.TP
.B -mpath path 
- Sets the path where the man pages will be written
.PD 1
.PD 0
.TP
.B -ext n      
- Sets the extension (1-9,l, etc)
.PD 1
.PD 0
.TP
.B -nolocation 
- Don't give the filename where the man page info was
.PD 1
.PD 0
.TP
.B -I filename 
- Filename contains the public includes needed by these
routines
.PD 1
.PD 0
.TP
.B -latex      
- Generate latex output rather than man format files
.PD 1
.PD 0
.TP
.B -html       
- Generate html (WWW) output rather than man format files
.PD 1
.PD 0
.TP
.B -man        
- Generate man (nroff) output (default)
.PD 1
.PD 0
.TP
.B -index filename 
- Generate a index file appropriate for tohtml
(for generating WWW files)
.PD 1
.PD 0
.TP
.B -defn defnfilename 
- Read commands from this file after loading the
default commands
.PD 1
.PD 0
.TP
.B -mapref filename 
- Read hyperlink database and apply to output
.PD 1
.PD 0
.TP
.B -indexdir dirname 
- 
Sets the root directory for the index file entries.
For example
.PD 1
.br
         -index foo.cit -indexdir \\"http://www.mcs.anl.gov/foo/man\\"
.PD 0
.TP
.B -outfile filename 
- 
Put the manpages in the indicated file
.PD 1
.PD 0
.TP
.B -heading name  
- Name for the heading (middle of top line)
.PD 1
.PD 0
.TP
.B -quotefmt      
- support '\\\\tt' and `\\\\em`
.PD 1
.PD 0
.TP
.B -oldargstyle    
- Allow multiple '. ' for an argument list, instead of
using '+  .... -' for argument lists with multiple
entries.
.PD 1
.PD 0
.TP
.B -skipprefix name 
- skip 'name' at the beginning of each line.  This
may be used for Fortran or Shell sources
.PD 1
.PD 0
.TP
.B -ignore string 
- skip 'name' in a function synopsis.  This can be used
to remove special keywords needed to build the routine
but not needed by the user (e.g., special export
keywords when building DLLs)
.PD 1
.PD 0
.TP
.B -keyword filename 
- 
Place keyword entries at the end of the specified file
.PD 1
.PD 0
.TP
.B -locdir directory 
- 
Uses directory in the Location: field
.PD 1
.PD 0
.TP
.B -dosnl 
- Generate DOS style files (return-newline instead of newline)
.PD 1
.PD 0
.TP
.B filenames 
- Names of the files from which documents are to be
extracted
.PD 1
.PD 0
.TP
.B -Wargdesc 
- Warn about arguments with no description
.PD 1
.PD 0
.TP
.B -Wnone  
- Turn off warnings
.PD 1

.SH LOCATION
doctext.cc
